### PR TITLE
simple setup.py

### PR DESCRIPTION
**Pull request by IuryAlves**

### CODE REVIEW

**Comment by kisielk** [comment]
@IuryAlves Thanks for PR, sorry for taking super long to notice it :) Are you still actively using this project?

**Comment by IuryAlves** [comment]
No problem =)
I used this project when i worked for a EdTech startup called QMágico. It's probably that they still use.

**Comment by kisielk** [comment]
Cool, interesting to hear that :) As you can probably guess I haven't touched this in quite a long time, so if anyone is using it in earnest, additional maintainers would be nice.

**Comment by IuryAlves** [comment]
I could be a maintainer =) I am always look for new projects to contribute.

**Pull request merged**
